### ISSUE TITLE
Manage favourites homebrews like original HBMenu

### ISSUE THREAD

**Issue by shadow2560** [ITotalJustice/sphaira#22]
It could be a nice add to have the favourites management as in the HBMenu, here is how I imagine it:
* When pressing "LS" or "RS" on a homebrew it will add/remove it from the favourites, it could be indicated in the menu by adding/removing a small star upper-left the homebrew name and creating/removing the empty file "homebrew_folder_path/.homebrew_file_name.star" witch indicate that the homebrew is a favourite or not (homebrews should be reordered after adding/removing one from favourites). An option could also be added to the "X" contextual menu to add/remove the homebrew from favourites.
* When scaning the homebrew list if the file "homebrew_folder_path/.homebrew_file_name.star" is present the homebrew is added to a list of favourites witch can be used to display or order it easily and the homebrew should be removed from the normal homebrews list.
* The favourite list should be ordered as order set in Sphayra options and should be displayed before the normal homebrews list.

With this logic it doesn't brake how Sphayra work and we can use favourites witch could be an usful function.

Last proposition, I think by default the homebrews should be ordered by name as in the HBMenu, when I launched Sphayra the first time it was difficult for me to understand the default sorting cause it was totaly different than on HBMenu (a problem specific to me cause of my visual impairement witch impose to learn my menus, the less the are modified the simplest it is for me).

Thanks for all and keep up the good work, I hope this homebrew will impose itself as a must have, I think it's on the good way, realy impressive work.

**Comment by ITotalJustice** [comment]
yes sorting by name by default is probably ideal. i sorted by timestamp as that's what i preferred, and its what hos (switch os) does. when you launch a game, it gets pushed to the front. when you install a game, it gets pushed to the front as you will likely want to play said game. i tried to replicate that in sphaira.

however, on the first launch of sphaira, apps will be sorted based on the install data of the .nro, which will seem like a random mess. only once you start launching apps will it start to sort itself out.

as for hbmenu stars, i did have code for this originally, but removed it because i am not really a fan of the star design. i can add it back with a few changes, it would work like this:

- Options -> Enable stars (on by default).
- when sorting the apps (timestamp, alphabetical etc), it will check to see if it has a star and stars are enabled, if so, it will be pushed to the top of the list.

would this be okay for you?

**Comment by ludothegreat** [comment]
I was never a fan of how hb handled favorite. Adding them to the front of the list made it feel clunky and bloated to me. Knowing that all the other stuff was just out of site drove my audhd insane. My personal preference would be to have a dedicated favorite screen that only the favs were listed and an option to load that (or any other screen for that matter) at launch. being able to navigate to it with how you setup the l&r buttons would be slick. If you were to implement it as you or og has describe I am very thankful you are also considering a feature to turn it off completely. 

Overall, everything you have done so far feel much faster, looks cleaner, and is very intuitive. I like the minimalist styling and the rather simple menus. the options make sense and everything seems to flow very well. thank you a ton for the work you have put into this.

**Comment by shadow2560** [comment]
For me your proposal is great. The proposal of star is to maintain compatibility and logic beetwen HBMenuu and Sphera, limiting the friction when passing from one to an other.

**Comment by ITotalJustice** [comment]
I have a new design in mind, it was inspired by another comment but I cant seem to find where I had seen it...

Change the sort options to have:
-  sort by name
- sort by updated
- sort by name + star
- sort by updated + star
This way, the new update won't break the order layout for people already using sphaira, whilst allowing new users to have the same layout as hbmenu, making the transition easier.

The next thing is to add a filter option:
- filter by all (shows everything)
- filter by favourites (only shows favourites)

**Comment by HenryBaby** [comment]
I'm not a big fan of the star design either, but I also found it useful as such. I agree with @shadow2560 about only displaying favourites not being particularly useful.

My personal choice would be a top "shelf" for the favourites as just a way of separating them from the rest of the homebrew.

**Comment by ITotalJustice** [comment]
https://github.com/user-attachments/assets/a99c7493-2cc1-4bfd-8f99-6f81a29be96d

this is the current version. i didn't implement the filter option mentioned above. for those that don't like stars, this doesn't change anything / slow down parsing as the path for checking if a .star exists only happens if the "star" order is set.

for those that want to have stars like hbmenu, you would set the "order" to "Alphabetical (star)". This will allow you to star / unstar using R3. A little star will be shown next to the name and a short notification appears when you do one of those actions.

the drop down menu shows the order options like so:
```c++
sort_items.push_back("Updated"_i18n);
sort_items.push_back("Alphabetical"_i18n);
sort_items.push_back("Updated (Star)"_i18n);
sort_items.push_back("Alphabetical (Star)"_i18n);
```
maybe it should be sorted like:
```c++
sort_items.push_back("Updated"_i18n);
sort_items.push_back("Updated (Star)"_i18n);
sort_items.push_back("Alphabetical"_i18n);
sort_items.push_back("Alphabetical (Star)"_i18n);
```
i would rather have it like:
```c++
sort_items.push_back("Alphabetical"_i18n);
sort_items.push_back("Alphabetical (Star)"_i18n);
sort_items.push_back("Updated"_i18n);
sort_items.push_back("Updated (Star)"_i18n);
```
however this last example would break peoples existing setup as the index value would change.

you may have noticed that i have removed the option to order via size. I figured its pretty pointless option that likely no one uses, its only useful for the filebrowser.

**Comment by ITotalJustice** [comment]
actually, maybe i should have stars *always* be enabled. if someone wants to disable stars, they can simple remove them all - i can even add an option to do that. that way the order options would just be:
```c++
sort_items.push_back("Updated"_i18n);
sort_items.push_back("Alphabetical"_i18n); // default
```

**Comment by shadow2560** [comment]
> actually, maybe i should have stars _always_ be enabled. if someone wants to disable stars, they can simple remove them all - i can even add an option to do that. that way the order options would just be:
> 
> ```c++
> sort_items.push_back("Updated"_i18n);
> sort_items.push_back("Alphabetical"_i18n); // default
> ```
> 
> this would incur slight overhead when parsing nro's as i have to check if a .star exists for every entry. this doesn't take long, as seen by how fast hbmenu can load - but it's still overhead for those that don't use .stars

That's why I proposed to have an option to just enable/disable star mode (enabled by default) independently of sort option, like that you have the better of the two worlds.

**Comment by ITotalJustice** [comment]
The problem I found with having a single toggle to enable/ disable them was that in order to make the transition better from hbmenu to sphaira, they have to be enabled by default. But this would mess the layout for everyone who has already installed sphaira. That's why I then decided to make it part of the order options

**Comment by shadow2560** [comment]
Could be understandable but they will just have to disable the option, for me it's the best compromize, the users of the HBMenu represent much more people than the users of Sphaira for now and users witch use star are probably a minority so for most users of Sphaira this will not change anything. But we can't have something witch unify everyone, a choice should be done.
