### ISSUE TITLE
features suggestion: allow use ZL & ZR key to jump pages in homebrew list like it works in appstore

### ISSUE THREAD

**Issue by WE1ZARD** [ITotalJustice/sphaira#53]
I really hope this can be impl into homebrew list as well,
it could be very handy for ppl who installed a lots nros.

btw, thanks for the star filter in the latest release, it's really useful.

**Comment by cucholix** [comment]
+1 extend the jump scrolling with ZL-ZR to file browser too if possible

**Comment by ITotalJustice** [comment]
i forgot i had that option in the appstore. do you actually like it? it current just jumps down a full page (9 entries) each frame, which makes it very hard to use imo. if i tap the button really quickly then it jumps about ~30-50 entries down, so i find it kinda hard to navigate with it.

maybe i should make it only jump down a single page on tapping, and have holding the button do nothing.

**Comment by WE1ZARD** [comment]
> i forgot i had that option in the appstore. do you actually like it? it current just jumps down a full page (9 entries) each frame, which makes it very hard to use imo. if i tap the button really quickly then it jumps about ~30-50 entries down, so i find it kinda hard to navigate with it.
> 
> maybe i should make it only jump down a single page on tapping, and have holding the button do nothing.

agree with ur idea of holding the button do nothing to avoid mis-tapping sometimes.
and YES, i believe this is a life change features if we can have it in furture updates.

**Comment by ITotalJustice** [comment]
i started to implement this, but the filebrowser currently uses ZR as a way to select multiple files (to be used with copy, delete, cut etc). the buttons currently in use are:

- A
- B
- X
- Y
- L1
- L2
- R1
- R2 

that only leaves the thumbstick button to select files, which idk doesn't feel great. you can accidentally move the thumbstick when clicking it for example.

Maybe i should change it so that clicking the thumbstick enters Selection mode, and pressing A will now select files, B to exit said mode. not really a fan of these either :/

**Comment by cucholix** [comment]
You can use d-pad left to jump scroll up, and d-pad-right to jump scroll down.

**Comment by ITotalJustice** [comment]
> You can use d-pad left to jump scroll up, and d-pad-right to jump scroll down.

ah yeah i didn't think of that. it won't be consistent with the other 2 menus, but i much prefer it over using the thumbstick
